/*  List of industries are based on LinkedIn industry list
    I retrieved the 2022 list from this site
        https://www.sage.exchange/post/linkedin-industries-list-rankings-2022
    Looks like it can change every year but I think it can probably be managed
    manually as it doesn;t look like it is changed much from year to year
*/
export enum Industry {
    Accounting = 'Accounting',
    AirlinesAviation = 'Airlines/Aviation',
    AlternativeDisputeResolution = 'Alternative Dispute Resolution',
    AlternativeMedicine = 'Alternative Medicine',
    Animation = 'Animation',
    ApparelFashion = 'Apparel & Fashion',
    ArchitecturePlanning = 'Architecture & Planning',
    ArtsAndCrafts = 'Arts and Crafts',
    Automotive = 'Automotive',
    AviationAerospace = 'Aviation & Aerospace',
    Banking = 'Banking',
    Biotechnology = 'Biotechnology',
    BroadcastMedia = 'Broadcast Media',
    BuildingMaterials = 'Building Materials',
    BusinessSuppliesAndEquipment = 'Business Supplies and Equipment',
    CapitalMarkets = 'Capital Markets',
    Chemicals = 'Chemicals',
    CivicSocialOrganization = 'Civic & Social Organization',
    CivilEngineering = 'Civil Engineering',
    CommercialRealEstate = 'Commercial Real Estate',
    ComputerNetworkSecurity = 'Computer & Network Security',
    ComputerGames = 'Computer Games',
    ComputerHardware = 'Computer Hardware',
    ComputerNetworking = 'Computer Networking',
    ComputerSoftware = 'Computer Software',
    Construction = 'Construction',
    ConsumerElectronics = 'Consumer Electronics',
    ConsumerGoods = 'Consumer Goods',
    ConsumerServices = 'Consumer Services',
    Cosmetics = 'Cosmetics',
    Dairy = 'Dairy',
    DefenseSpace = 'Defense & Space',
    Design = 'Design',
    ELearning = 'E-Learning',
    EducationManagement = 'Education Management',
    ElectricalElectronicManufacturing = 'Electrical/Electronic Manufacturing',
    Entertainment = 'Entertainment',
    EnvironmentalServices = 'Environmental Services',
    EventsServices = 'Events Services',
    ExecutiveOffice = 'Executive Office',
    FacilitiesServices = 'Facilities Services',
    Farming = 'Farming',
    FinancialServices = 'Financial Services',
    FineArt = 'Fine Art',
    Fishery = 'Fishery',
    FoodBeverages = 'Food & Beverages',
    FoodProduction = 'Food Production',
    FundRaising = 'Fund-Raising',
    Furniture = 'Furniture',
    GamblingCasinos = 'Gambling & Casinos',
    GlassCeramicsConcrete = 'Glass, Ceramics & Concrete',
    GovernmentAdministration = 'Government Administration',
    GovernmentRelations = 'Government Relations',
    GraphicDesign = 'Graphic Design',
    HealthWellnessAndFitness = 'Health, Wellness and Fitness',
    HigherEducation = 'Higher Education',
    HospitalHealthCare = 'Hospital & Health Care',
    Hospitality = 'Hospitality',
    HumanResources = 'Human Resources',
    ImportAndExport = 'Import and Export',
    IndividualFamilyServices = 'Individual & Family Services',
    IndustrialAutomation = 'Industrial Automation',
    InformationServices = 'Information Services',
    Insurance = 'Insurance',
    InternationalAffairs = 'International Affairs',
    InternationalTradeAndDevelopment = 'International Trade and Development',
    Internet = 'Internet',
    InvestmentBanking = 'Investment Banking',
    InvestmentManagement = 'Investment Management',
    Judiciary = 'Judiciary',
    LawEnforcement = 'Law Enforcement',
    LawPractice = 'Law Practice',
    LegalServices = 'Legal Services',
    LegislativeOffice = 'Legislative Office',
    LeisureTravelTourism = 'Leisure, Travel & Tourism',
    Libraries = 'Libraries',
    LogisticsAndSupplyChain = 'Logistics and Supply Chain',
    LuxuryGoodsJewelry = 'Luxury Goods & Jewelry',
    Machinery = 'Machinery',
    ManagementConsulting = 'Management Consulting',
    Maritime = 'Maritime',
    MarketResearch = 'Market Research',
    MarketingAndAdvertising = 'Marketing and Advertising',
    MechanicalorIndustrialEngineering = 'Mechanical or Industrial Engineering',
    MediaProduction = 'Media Production',
    MedicalDevices = 'Medical Devices',
    MedicalPractice = 'Medical Practice',
    MentalHealthCare = 'Mental Health Care',
    Military = 'Military',
    MiningMetals = 'Mining & Metals',
    MobileGames = 'Mobile Games',
    MotionPicturesAndFilm = 'Motion Pictures and Film',
    MuseumsAndInstitutions = 'Museums and Institutions',
    Music = 'Music',
    Nanotechnology = 'Nanotechnology',
    Newspapers = 'Newspapers',
    NonProfitOrganizationManagement = 'Non-Profit Organization Management',
    OilEnergy = 'Oil & Energy',
    OnlineMedia = 'Online Media',
    OutsourcingOffshoring = 'Outsourcing/Offshoring',
    PackageFreightDelivery = 'Package/Freight Delivery',
    PackagingAndContainers = 'Packaging and Containers',
    PaperForestProducts = 'Paper & Forest Products',
    PerformingArts = 'Performing Arts',
    Pharmaceuticals = 'Pharmaceuticals',
    Philanthropy = 'Philanthropy',
    Photography = 'Photography',
    Plastics = 'Plastics',
    PoliticalOrganization = 'Political Organization',
    PrimarySecondaryEducation = 'Primary/Secondary Education',
    Printing = 'Printing',
    ProfessionalTrainingCoaching = 'Professional Training & Coaching',
    ProgramDevelopment = 'Program Development',
    PublicPolicy = 'Public Policy',
    PublicRelationsAndCommunications = 'Public Relations and Communications',
    PublicSafety = 'Public Safety',
    Publishing = 'Publishing',
    RailroadManufacture = 'Railroad Manufacture',
    Ranching = 'Ranching',
    RealEstate = 'Real Estate',
    RecreationalFacilitiesAndServices = 'Recreational Facilities and Services',
    ReligiousInstitutions = 'Religious Institutions',
    RenewablesEnvironment = 'Renewables & Environment',
    Research = 'Research',
    Restaurants = 'Restaurants',
    Retail = 'Retail',
    SecurityAndInvestigations = 'Security and Investigations',
    Semiconductors = 'Semiconductors',
    Shipbuilding = 'Shipbuilding',
    SportingGoods = 'Sporting Goods',
    Sports = 'Sports',
    StaffingAndRecruiting = 'Staffing and Recruiting',
    Supermarkets = 'Supermarkets',
    Telecommunications = 'Telecommunications',
    Textiles = 'Textiles',
    ThinkTanks = 'Think Tanks',
    Tobacco = 'Tobacco',
    TranslationAndLocalization = 'Translation and Localization',
    TransportationTruckingRailroad = 'Transportation/Trucking/Railroad',
    Utilities = 'Utilities',
    VentureCapitalPrivateEquity = 'Venture Capital & Private Equity',
    Veterinary = 'Veterinary',
    Warehousing = 'Warehousing',
    Wholesale = 'Wholesale',
    WineAndSpirits = 'Wine and Spirits',
    Wireless = 'Wireless',
    WritingAndEditing = 'Writing and Editing',
}

export const IndustriesMap = Object.keys(Industry).map((name) => {
    return {
        name,
        value: Industry[name as keyof typeof Industry],
    };
});

